# Generated by Django 3.2.10 on 2024-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'expense_types',
            },
        ),
    ]
