# Generated by Django 3.2.10 on 2024-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=255)),
                ('supplierNO', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('altPhone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('openingBalance', models.CharField(max_length=255)),
                ('payTerm', models.CharField(max_length=255)),
                ('payCategory', models.CharField(max_length=255)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
    ]
