# Generated by Django 3.2.10 on 2024-02-22 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('regNumber', models.CharField(max_length=255)),
                ('studentGender', models.CharField(max_length=255)),
                ('deleteFlag', models.CharField(default='N', max_length=1)),
                ('transferFlag', models.CharField(default='N', max_length=1)),
                ('dob', models.DateField()),
                ('dateOfAdmission', models.DateField()),
                ('healthStatus', models.CharField(max_length=255)),
                ('classID', models.IntegerField()),
                ('streamID', models.IntegerField()),
                ('schoolStatus', models.CharField(max_length=255)),
                ('dormitory', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='StudentsAvatar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgURL', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'db_table': 'studentsavatar',
            },
        ),
    ]
