# Generated by Django 3.2.10 on 2024-02-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feecategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feecategories.feecategories')),
            ],
            options={
                'db_table': 'payment_groups',
            },
        ),
    ]
