# Generated by Django 3.2.10 on 2024-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('current_session', models.CharField(max_length=20)),
                ('school_type', models.CharField(choices=[('Preprimary', 'Preprimary'), ('Primary', 'Primary'), ('Junior Secondary', 'Junior Secondary'), ('Senior Secondary', 'Senior Secondary'), ('Tertiary', 'Tertiary')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'System Information',
                'db_table': 'system_info',
            },
        ),
    ]
