# Generated by Django 3.2.10 on 2024-02-22 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentName', models.CharField(max_length=250)),
                ('parentIdno', models.CharField(max_length=250)),
                ('parentPhone', models.CharField(max_length=250)),
                ('firstLogin', models.CharField(default='Y', max_length=1)),
                ('deletedFlag', models.CharField(default='N', max_length=1)),
                ('status', models.BooleanField(default=True)),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parents',
            },
        ),
        migrations.CreateModel(
            name='ParentsAvatar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgURL', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'parentsavatar',
            },
        ),
    ]
