# Generated by Django 3.2.10 on 2024-02-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentType', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian'), ('Sponsor', 'Sponsor')], max_length=8)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('parentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parents')),
            ],
        ),
    ]
