# Generated by Django 3.2.10 on 2024-02-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systeminfo', '0001_initial'),
        ('feecategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceNO', models.CharField(max_length=100)),
                ('amountPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datePosted', models.DateField(auto_now_add=True)),
                ('feeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feecategories.feecategories')),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systeminfo.systeminfo')),
            ],
            options={
                'verbose_name_plural': 'Fee Payments',
                'db_table': 'fee_payments',
            },
        ),
    ]
